services:
  neo4j:
    image: neo4j:latest
    volumes:
    - ./logs:/logs
    - ./config:/config
    - ./data:/data
    - ./plugin:/plugins
    environment:
    - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
    - "7474:7474"
    - "7687:7687"
    restart: always
    secrets:
    - neo4j_auth_file
secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt